### ISSUE TITLE
I usually use Cerberus to validate the json schema

### ISSUE THREAD

**Issue by ghost** [kashifusmani/interview_prep#4]
This just makes it cleaner than this, but for interviews, you can keep it the same if you want. Or may be writing a comment to use something like the following package would be enough
https://docs.python-cerberus.org/en/stable/

https://github.com/kashifusmani/interview_prep/blob/f1bcf65cf6eee6b12a47d75caf9a51301eecdd5a/punchh/app/data_loader.py#L38

**Comment by kashifusmani** [comment]
done
